-- SELECT with AND clause

-- SETUP


-- SOLUTION: SELECT * FROM foxtrot WHERE MRRANK_RANK>400 AND TTY='SY' OR TTY='PT';



INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('405', 'RXNORM', 'SY', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('396', 'HPO', 'PT', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('386', 'ATC', 'PT', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('385', 'VANDF', 'PT', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('379', 'USPMG', 'PT', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('372', 'FMA', 'PT', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('367', 'UWDA', 'PT', 'N');


INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('411', 'RXNORM', 'DF', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('410', 'RXNORM', 'SBDC', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('409', 'RXNORM', 'BN', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('408', 'RXNORM', 'PIN', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('407', 'RXNORM', 'BPCK', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('406', 'RXNORM', 'GPCK', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('404', 'RXNORM', 'TMSY', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('403', 'MSH', 'MH', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('402', 'MSH', 'TQ', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('401', 'MSH', 'PEP', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('400', 'MSH', 'ET', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('399', 'MSH', 'XQ', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('398', 'MSH', 'PXQ', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('397', 'MSH', 'NM', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('395', 'HPO', 'SY', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('394', 'HPO', 'ET', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('393', 'HPO', 'OP', 'Y');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('392', 'HPO', 'IS', 'Y');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('391', 'NCBI', 'SCN', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('390', 'MTHSPL', 'MTH_RXN_DP', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('389', 'MTHSPL', 'DP', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('388', 'MTHSPL', 'SU', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('387', 'ATC', 'RXN_PT', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('384', 'VANDF', 'CD', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('383', 'VANDF', 'IN', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('382', 'USP', 'CD', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('381', 'USP', 'IN', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('380', 'USPMG', 'HC', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('378', 'DRUGBANK', 'IN', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('377', 'DRUGBANK', 'SY', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('376', 'DRUGBANK', 'FSY', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('375', 'MSH', 'N1', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('374', 'MSH', 'PCE', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('373', 'MSH', 'CE', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('371', 'FMA', 'SY', 'N');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('370', 'FMA', 'AB', 'Y');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('369', 'FMA', 'OP', 'Y');

INSERT INTO foxtrot (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('368', 'FMA', 'IS', 'Y');




-- GOAL:




INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('405', 'RXNORM', 'SY', 'N');

INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('396', 'HPO', 'PT', 'N');

INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('386', 'ATC', 'PT', 'N');

INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('385', 'VANDF', 'PT', 'N');

INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('379', 'USPMG', 'PT', 'N');

INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('372', 'FMA', 'PT', 'N');

INSERT INTO foxtrotd (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('367', 'UWDA', 'PT', 'N');

-- HIDDEN TESTS




INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('411', 'NCI_CTRP', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('510', 'NCI_CTRP', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('808', 'NCI_FDA', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('607', 'NCI_FDA', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('305', 'NCI_GENC', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('502', 'NCI_CRCH', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('300', 'NCI_DICOM', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('499', 'NCI_CDISC-GLOSS', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('797', 'NCI_BRIDG', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('294', 'NCI_BioC', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('292', 'NCI_CTCAE', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('991', 'NCI_EDQM-HC', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('489', 'NCI_CTCAE_5', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('288', 'NCI_CTCAE_3', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('287', 'NCI_CTEP-SDC', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('886', 'NCI_CTEP-SDC', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('284', 'NCI_JAX', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('582', 'NCI_KEGG', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('280', 'NCI_ICH', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('278', 'NCI_NCI-HGNC', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('477', 'NCI_NCI-HGNC', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('276', 'NCI_NCI-HL7', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('674', 'NCI_UCUM', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('371', 'NCI_NICHD', 'PT', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('409', 'NCI_CTRP', 'DN', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('306', 'NCI', 'HD', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('104', 'NCI_GENC', 'CA2', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('303', 'NCI_GENC', 'CA3', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('301', 'NCI_CRCH', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('298', 'NCI_CDISC-GLOSS', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('296', 'NCI_BRIDG', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('695', 'NCI_RENI', 'DN', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('293', 'NCI', 'CCN', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('290', 'NCI_EDQM-HC', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('285', 'NCI', 'CCS', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('283', 'NCI_JAX', 'SY', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('281', 'NCI_ICH', 'AB', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('179', 'NCI_NCI-HL7', 'AB', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('275', 'NCI_UCUM', 'AB', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('273', 'NCI_KEGG', 'AB', 'N');

INSERT INTO foxtrot2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('272', 'NCI_KEGG', 'SY', 'N');



-- GOAL 2:




INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('411', 'NCI_CTRP', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('510', 'NCI_CTRP', 'SY', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('808', 'NCI_FDA', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('607', 'NCI_FDA', 'SY', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('305', 'NCI_GENC', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('502', 'NCI_CRCH', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('300', 'NCI_DICOM', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('499', 'NCI_CDISC-GLOSS', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('797', 'NCI_BRIDG', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('294', 'NCI_BioC', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('292', 'NCI_CTCAE', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('991', 'NCI_EDQM-HC', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('489', 'NCI_CTCAE_5', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('288', 'NCI_CTCAE_3', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('287', 'NCI_CTEP-SDC', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('886', 'NCI_CTEP-SDC', 'SY', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('284', 'NCI_JAX', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('582', 'NCI_KEGG', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('280', 'NCI_ICH', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('278', 'NCI_NCI-HGNC', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('477', 'NCI_NCI-HGNC', 'SY', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('276', 'NCI_NCI-HL7', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('674', 'NCI_UCUM', 'PT', 'N');

INSERT INTO foxtrot2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('371', 'NCI_NICHD', 'PT', 'N');
