-- Compound WHERE clauses

-- SOLUTION: SELECT * FROM echo WHERE MRRANK_RANK<380 OR TTY='CD';

-- SETUP
INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('384', 'VANDF', 'CD', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('382', 'USP', 'CD', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('379', 'USPMG', 'PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('378', 'DRUGBANK', 'IN', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('377', 'DRUGBANK', 'SY', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('376', 'DRUGBANK', 'FSY', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('375', 'MSH', 'N1', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('374', 'MSH', 'PCE', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('373', 'MSH', 'CE', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('372', 'FMA', 'PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('371', 'FMA', 'SY', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('370', 'FMA', 'AB', 'Y');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('369', 'FMA', 'OP', 'Y');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('368', 'FMA', 'IS', 'Y');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('367', 'UWDA', 'PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('411', 'RXNORM', 'DF', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('410', 'RXNORM', 'SBDC', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('409', 'RXNORM', 'BN', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('408', 'RXNORM', 'PIN', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('407', 'RXNORM', 'BPCK', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('406', 'RXNORM', 'GPCK', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('405', 'RXNORM', 'SY', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('404', 'RXNORM', 'TMSY', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('403', 'MSH', 'MH', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('402', 'MSH', 'TQ', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('401', 'MSH', 'PEP', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('400', 'MSH', 'ET', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('399', 'MSH', 'XQ', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('398', 'MSH', 'PXQ', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('397', 'MSH', 'NM', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('396', 'HPO', 'PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('395', 'HPO', 'SY', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('394', 'HPO', 'ET', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('393', 'HPO', 'OP', 'Y');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('392', 'HPO', 'IS', 'Y');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('391', 'NCBI', 'SCN', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('390', 'MTHSPL', 'MTH_RXN_DP', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('389', 'MTHSPL', 'DP', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('388', 'MTHSPL', 'SU', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('387', 'ATC', 'RXN_PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('386', 'ATC', 'PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('385', 'VANDF', 'PT', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('383', 'VANDF', 'IN', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('381', 'USP', 'IN', 'N');

INSERT INTO echo (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('380', 'USPMG', 'HC', 'N');


-- GOAL:

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('384', 'VANDF', 'CD', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('382', 'USP', 'CD', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('379', 'USPMG', 'PT', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('378', 'DRUGBANK', 'IN', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('377', 'DRUGBANK', 'SY', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('376', 'DRUGBANK', 'FSY', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('375', 'MSH', 'N1', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('374', 'MSH', 'PCE', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('373', 'MSH', 'CE', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('372', 'FMA', 'PT', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('371', 'FMA', 'SY', 'N');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('370', 'FMA', 'AB', 'Y');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('369', 'FMA', 'OP', 'Y');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('368', 'FMA', 'IS', 'Y');

INSERT INTO echod (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('367', 'UWDA', 'PT', 'N');


-- HIDDEN TESTS

-- SETUP 2



INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('345', 'CHV', 'PT', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('442', 'ICPC', 'CD', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('340', 'ICPC', 'PS', 'Y');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('239', 'ICPC', 'PC', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('637', 'ICPC', 'CD', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('234', 'ICPC', 'CO', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('333', 'AOT', 'PT', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('232', 'AOT', 'ET', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('230', 'HCPCS', 'OM', 'Y');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('229', 'HCPCS', 'OAM', 'Y');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('227', 'GO', 'MTH_PT', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('626', 'GO', 'CD', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('446', 'PDQ', 'SY', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('444', 'MEDLINEPLUS', 'PT', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('443', 'SOP', 'PT', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('441', 'ICPC', 'PT', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('380', 'ICPC', 'CX', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('381', 'ICPC', 'CS', 'Y');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('735', 'ICPC', 'CC', 'N');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('531', 'HCPCS', 'OP', 'Y');

INSERT INTO echo2 (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('428', 'GO', 'PT', 'N');

-- GOAL 2


INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('345', 'CHV', 'PT', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('442', 'ICPC', 'CD', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('340', 'ICPC', 'PS', 'Y');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('239', 'ICPC', 'PC', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('637', 'ICPC', 'CD', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('234', 'ICPC', 'CO', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('333', 'AOT', 'PT', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('232', 'AOT', 'ET', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('230', 'HCPCS', 'OM', 'Y');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('229', 'HCPCS', 'OAM', 'Y');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('227', 'GO', 'MTH_PT', 'N');

INSERT INTO echo2d (MRRANK_RANK, SAB, TTY, SUPPRESS) 
VALUES ('626', 'GO', 'CD', 'N');
